WITH SAVED AS
  (SELECT SUBJECT_ID,
    GROUP_NAME,
    OBJECT_NAME,
    OBJECT_TYPE,
    OBJECT_SUBTYPE,
    OBJECT_ID,
    VERSION_NUMBER
  FROM $metaOwner.OPB_VERSION_PROPS
  WHERE USER_ID =
    (SELECT ID
    FROM $metaOwner.OPB_USER_GROUP
    WHERE TYPE      = 1
    AND STATUS      = 0
    AND LOWER(NAME) = '$adminUser'
    )
  AND UTC_LAST_SAVED >= $startUTCStr
  ),
  INFAOBJ AS
  (SELECT SAVED.SUBJECT_ID,
    SAVED.GROUP_NAME
    || '.'
    || SAVED.OBJECT_NAME OBJECT_NAME,
    SAVED.OBJECT_TYPE,
    SAVED.VERSION_NUMBER,
    2 IS_REUSABLE
  FROM $metaOwner.OPB_SRC SRC,
    SAVED
  WHERE SAVED.OBJECT_ID    = SRC.SRC_ID
  AND SAVED.OBJECT_TYPE    = 1
  AND SAVED.VERSION_NUMBER = SRC.VERSION_NUMBER
  AND SRC.IS_VISIBLE       = 1
  UNION
  SELECT SAVED.SUBJECT_ID,
    SAVED.OBJECT_NAME,
    SAVED.OBJECT_TYPE,
    SAVED.VERSION_NUMBER,
    2 IS_REUSABLE
  FROM $metaOwner.OPB_TARG TARG,
    SAVED
  WHERE SAVED.OBJECT_ID    = TARG.TARGET_ID
  AND SAVED.OBJECT_TYPE    = 2
  AND SAVED.VERSION_NUMBER = TARG.VERSION_NUMBER
  AND TARG.IS_VISIBLE      = 1
  UNION
  SELECT SAVED.SUBJECT_ID,
    SAVED.OBJECT_NAME,
    SAVED.OBJECT_TYPE,
    SAVED.VERSION_NUMBER,
    TRANS.IS_REUSABLE IS_REUSABLE
  FROM $metaOwner.OPB_WIDGET TRANS,
    SAVED
  WHERE SAVED.OBJECT_ID = TRANS.WIDGET_ID
  AND SAVED.OBJECT_TYPE BETWEEN 3 AND 17
  AND SAVED.VERSION_NUMBER = TRANS.VERSION_NUMBER
  AND TRANS.IS_VISIBLE     = 1
  AND TRANS.IS_REUSABLE    = 1
  UNION
  SELECT SAVED.SUBJECT_ID,
    SAVED.OBJECT_NAME,
    SAVED.OBJECT_TYPE,
    SAVED.VERSION_NUMBER,
    2 IS_REUSABLE
  FROM $metaOwner.OPB_MAPPING MAPG,
    SAVED
  WHERE SAVED.OBJECT_ID    = MAPG.MAPPING_ID
  AND SAVED.OBJECT_TYPE    = 21
  AND SAVED.VERSION_NUMBER = MAPG.VERSION_NUMBER
  AND MAPG.IS_VISIBLE      = 1
  UNION
  SELECT SAVED.SUBJECT_ID,
    SAVED.OBJECT_NAME,
    SAVED.OBJECT_TYPE,
    SAVED.VERSION_NUMBER,
    TASK.IS_REUSABLE IS_REUSABLE
  FROM $metaOwner.OPB_TASK TASK,
    SAVED
  WHERE SAVED.OBJECT_ID = TASK.TASK_ID
  AND SAVED.OBJECT_TYPE BETWEEN 58 AND 71
  AND SAVED.VERSION_NUMBER = TASK.VERSION_NUMBER
  AND TASK.IS_VISIBLE      = 1
  AND TASK.IS_REUSABLE     = 1
  UNION
  -- Shortcuts
  SELECT SAVED.SUBJECT_ID,
    CASE
      WHEN SAVED.GROUP_NAME IS NOT NULL
      THEN SAVED.GROUP_NAME
        || '.'
        || SAVED.OBJECT_NAME
      ELSE SAVED.OBJECT_NAME
    END OBJECT_NAME,
    SAVED.OBJECT_SUBTYPE,
    SAVED.VERSION_NUMBER,
    2 IS_REUSABLE
  FROM $metaOwner.OPB_SHORTCUT SHORTCUT,
    SAVED
  WHERE SAVED.OBJECT_ID = SHORTCUT.OBJECT_ID
  AND SAVED.OBJECT_TYPE BETWEEN 23 AND 25
  AND SAVED.VERSION_NUMBER = SHORTCUT.VERSION_NUMBER
  AND SHORTCUT.IS_VISIBLE  = 1
  )
SELECT SUBJ.SUBJ_NAME
  || ','
  || INFAOBJ.OBJECT_NAME
  || ','
  || INFAOBJ.OBJECT_TYPE
  || ','
  || INFAOBJ.VERSION_NUMBER
  || ','
  || INFAOBJ.IS_REUSABLE RES
FROM INFOMETA.OPB_SUBJECT SUBJ,
  INFAOBJ
WHERE SUBJ.SUBJ_ID = INFAOBJ.SUBJECT_ID