SELECT SUBJ.SUBJ_NAME
  || ','
  || TARG.TARGET_NAME
  || ','
  || FLD.FLDNO
  || ','
  || FLD.TARGET_NAME
  || ','
  || DTYPE.DATATYPE_NAME
  || ','
  || FLD.DPREC
  || ','
  || FLD.DSCALE
  || ','
  || FLD.NULLTYPE
  || ','
  || FLD.KEYTYPE RES
FROM $metaOwner.OPB_TARG TARG,
  $metaOwner.OPB_TARG_FLD FLD,
  $metaOwner.OPB_MMD_DATATYPE DTYPE,
  $metaOwner.OPB_SUBJECT SUBJ
WHERE TARG.TARGET_ID       = FLD.TARGET_ID
AND FLD.NDTYPE      = DTYPE.NATIVE_DATATYPE
AND FLD.DTYPE       = DTYPE.PM_DATATYPE
AND TARG.VERSION_NUMBER = FLD.VERSION_NUMBER
AND TARG.SUBJ_ID        = SUBJ.SUBJ_ID
AND DTYPE.PROP_FLAGS   <> 128
AND TARG.IS_VISIBLE     = 1
AND SUBJ.SUBJ_NAME
  || ','
  ||TARG.TARGET_NAME IN ($tgtListStr)