SELECT SUBJ.SUBJ_NAME
  || ','
  || SRC.SOURCE_NAME
  || ','
  || FLD.FLDNO
  || ','
  || FLD.SRC_NAME
  || ','
  || DTYPE.DATATYPE_NAME
  || ','
  || PIC.SRC_PREC
  || ','
  || PIC.SRC_SCALE
  || ','
  || FLD.NULLTYPE
  || ','
  || FLD.KEYTYPE RES
FROM $metaOwner.OPB_SRC SRC,
  $metaOwner.OPB_SRC_FLD FLD,
  $metaOwner.OPB_PICDSC PIC,
  $metaOwner.OPB_MMD_DATATYPE DTYPE,
  $metaOwner.OPB_SUBJECT SUBJ
WHERE SRC.SRC_ID       = FLD.SRC_ID
AND FLD.PICID          = PIC.PICID
AND PIC.SRC_NTYPE      = DTYPE.NATIVE_DATATYPE
AND PIC.SRC_TYPE       = DTYPE.PM_DATATYPE
AND SRC.VERSION_NUMBER = FLD.VERSION_NUMBER
AND SRC.VERSION_NUMBER = PIC.VERSION_NUMBER
AND SRC.SUBJ_ID        = SUBJ.SUBJ_ID
AND DTYPE.PROP_FLAGS   <> 128
AND SRC.IS_VISIBLE     = 1
AND SUBJ.SUBJ_NAME
  || ','
  ||SRC.SOURCE_NAME IN ($srcListStr)