WITH LABEL AS
  (SELECT B.OBJECT_ID,
    B.OBJECT_TYPE,
    B.VERSION_NUMBER,
    B.SUBJECT_ID
  FROM $metaOwner.REP_LABEL A
  INNER JOIN $metaOwner.REP_LABEL_REF B
  ON A.LABEL_ID      = B.LABEL_ID
  WHERE A.LABEL_NAME = '$crq'
  ),
  INFAOBJ AS
  (SELECT SRC.SUBJ_ID SUBJ_ID,
    SRC.SOURCE_NAME OBJ_NAME,
    'source' OBJ_TYPE,
    SRC.IS_VISIBLE,
    SRC.VERSION_NUMBER - LABEL.VERSION_NUMBER IS_LABEL
  FROM $metaOwner.OPB_SRC SRC,
    LABEL
  WHERE LABEL.OBJECT_ID  = SRC.SRC_ID
  AND LABEL.SUBJECT_ID   = SRC.SUBJ_ID
  AND SRC.VERSION_NUMBER =
    (SELECT MAX(VERSION_NUMBER)
    FROM $metaOwner.OPB_SRC
    WHERE SRC_ID = SRC.SRC_ID
    AND SUBJ_ID  =SRC.SUBJ_ID
    )
  UNION
  SELECT TARG.SUBJ_ID SUBJ_ID,
    TARG.TARGET_NAME OBJ_NAME,
    'target' OBJ_TYPE,
    TARG.IS_VISIBLE ,
    TARG.VERSION_NUMBER - LABEL.VERSION_NUMBER IS_LABEL
  FROM $metaOwner.OPB_TARG TARG,
    LABEL
  WHERE LABEL.OBJECT_ID   = TARG.TARGET_ID
  AND LABEL.SUBJECT_ID    = TARG.SUBJ_ID
  AND TARG.VERSION_NUMBER =
    (SELECT MAX(VERSION_NUMBER)
    FROM $metaOwner.OPB_TARG
    WHERE TARGET_ID = TARG.TARGET_ID
    AND SUBJ_ID     = TARG.SUBJ_ID
    )
  UNION
  SELECT TRANS.SUBJECT_ID SUBJ_ID,
    TRANS.WIDGET_NAME OBJ_NAME,
    'transformation' OBJ_TYPE,
    TRANS.IS_VISIBLE ,
    TRANS.VERSION_NUMBER - LABEL.VERSION_NUMBER IS_LABEL
  FROM $metaOwner.OPB_WIDGET TRANS,
    LABEL
  WHERE LABEL.OBJECT_ID    = TRANS.WIDGET_ID
  AND LABEL.OBJECT_TYPE    = TRANS.WIDGET_TYPE
  AND LABEL.SUBJECT_ID     = TRANS.SUBJECT_ID
  AND TRANS.VERSION_NUMBER =
    (SELECT MAX(VERSION_NUMBER)
    FROM $metaOwner.OPB_WIDGET
    WHERE WIDGET_ID = TRANS.WIDGET_ID
    AND WIDGET_TYPE = TRANS.WIDGET_TYPE
    AND SUBJECT_ID  = TRANS.SUBJECT_ID
    )
  UNION
  SELECT MAPG.SUBJECT_ID SUBJ_ID,
    MAPG.MAPPING_NAME OBJ_NAME,
    'mapping' OBJ_TYPE,
    MAPG.IS_VISIBLE ,
    MAPG.VERSION_NUMBER - LABEL.VERSION_NUMBER IS_LABEL
  FROM $metaOwner.OPB_MAPPING MAPG,
    LABEL
  WHERE LABEL.OBJECT_ID   = MAPG.MAPPING_ID
  AND LABEL.SUBJECT_ID    = MAPG.SUBJECT_ID
  AND MAPG.VERSION_NUMBER =
    (SELECT MAX(VERSION_NUMBER)
    FROM $metaOwner.OPB_MAPPING
    WHERE MAPPING_ID = MAPG.MAPPING_ID
    AND SUBJECT_ID   = MAPG.SUBJECT_ID
    )
  UNION
  SELECT TASK.SUBJECT_ID SUBJ_ID,
    TASK.TASK_NAME,
    CASE TASK.TASK_TYPE
      WHEN 58
      THEN 'task'
      WHEN 68
      THEN 'session'
      WHEN 70
      THEN 'worklet'
      WHEN 71
      THEN 'workflow'
      ELSE NULL
    END OBJ_TYPE,
    TASK.IS_VISIBLE,
    TASK.VERSION_NUMBER - LABEL.VERSION_NUMBER IS_LABEL
  FROM $metaOwner.OPB_TASK TASK,
    LABEL
  WHERE LABEL.OBJECT_ID   = TASK.TASK_ID
  AND LABEL.SUBJECT_ID    = TASK.SUBJECT_ID
  AND LABEL.OBJECT_TYPE   = TASK.TASK_TYPE
  AND TASK.VERSION_NUMBER =
    (SELECT MAX(VERSION_NUMBER)
    FROM $metaOwner.OPB_TASK
    WHERE TASK_ID  = TASK.TASK_ID
    AND SUBJECT_ID = TASK.SUBJECT_ID
    AND TASK_TYPE  = TASK.TASK_TYPE
    )
  UNION
  SELECT SHORTCUT.SUBJECT_ID SUBJ_ID,
    SHORTCUT.SHORTCUT_NAME OBJ_NAME,
    CASE SHORTCUT.OBJECT_TYPE
      WHEN 23
      THEN 'TRANS_SC'
      WHEN 24
      THEN 'TARGET_SC'
      WHEN 25
      THEN 'SOURCE_SC'
      ELSE NULL
    END OBJ_TYPE,
    SHORTCUT.IS_VISIBLE,
    SHORTCUT.VERSION_NUMBER - LABEL.VERSION_NUMBER IS_LABEL
  FROM $metaOwner.OPB_SHORTCUT SHORTCUT,
    LABEL
  WHERE LABEL.OBJECT_ID       = SHORTCUT.OBJECT_ID
  AND LABEL.OBJECT_TYPE       = SHORTCUT.OBJECT_TYPE
  AND LABEL.SUBJECT_ID        = SHORTCUT.SUBJECT_ID
  AND SHORTCUT.VERSION_NUMBER =
    (SELECT MAX(VERSION_NUMBER)
    FROM $metaOwner.OPB_SHORTCUT
    WHERE OBJECT_ID = SHORTCUT.OBJECT_ID
    AND OBJECT_TYPE = SHORTCUT.OBJECT_TYPE
    AND SUBJECT_ID  = SHORTCUT.SUBJECT_ID
    )
  )
SELECT SUBJ.SUBJ_NAME || ',' ||
  INFAOBJ.OBJ_NAME || ',' ||
  INFAOBJ.OBJ_TYPE || ',' ||
  INFAOBJ.IS_VISIBLE || ',' ||
  INFAOBJ.IS_LABEL RES
FROM $metaOwner.OPB_SUBJECT SUBJ,
  INFAOBJ
WHERE SUBJ.SUBJ_ID = INFAOBJ.SUBJ_ID
